server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lingogame
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true

  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 4
        order_inserts: true
    hibernate:
      ddl-auto: update


